--Context

USE EDW.EDW_EXTR;

--EDW_EXTR EMPLOYEE_DETAILS VIEW 

CREATE OR REPLACE VIEW EDW_EXTR.EMP_DETAILS_VIEW ("EMPLOYEE_ID", "JOB_ID", "MANAGER_ID", "DEPARTMENT_ID", "LOCATION_ID", 
"COUNTRY_ID", "FIRST_NAME", "LAST_NAME", "SALARY", "COMMISSION_PCT", "DEPARTMENT_NAME", "JOB_TITLE", "CITY", "STATE_PROVINCE", 
"COUNTRY_NAME", "REGION_NAME") AS 
  SELECT  
  E.EMPLOYEE_ID,   
  E.JOB_ID,   
  E.MANAGER_ID,   
  E.DEPARTMENT_ID,  
  D.LOCATION_ID,  
  L.COUNTRY_ID,  
  E.FIRST_NAME,  
  E.LAST_NAME,  
  E.SALARY,  
  E.COMMISSION_PCT,  
  D.DEPARTMENT_NAME,  
  J.JOB_TITLE,  
  L.CITY,  
  L.STATE_PROVINCE,  
  C.COUNTRY_NAME,  
  R.REGION_NAME  
FROM  
  EDW.EMPLOYEES E,  
  EDW.DEPARTMENTS D,  
  EDW.JOBS J,  
  EDW.LOCATIONS L,  
  EDW.COUNTRIES C,  
  EDW.REGIONS R  
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  
  AND D.LOCATION_ID = L.LOCATION_ID  
  AND L.COUNTRY_ID = C.COUNTRY_ID  
  AND C.REGION_ID = R.REGION_ID  
  AND J.JOB_ID = E.JOB_ID   
;



--Dynamic Table Example to get the employee details updated for repoting need.

CREATE OR REPLACE DYNAMIC TABLE EMPLOYEE_DETAILS(
	EMPLOYEE_ID,
	JOB_ID,
	MANAGER_ID,
	DEPARTMENT_ID,
	LOCATION_ID,
	COUNTRY_ID,
	FIRST_NAME,
	LAST_NAME,
	SALARY,
	COMMISSION_PCT,
	DEPARTMENT_NAME,
	JOB_TITLE,
	CITY,
	STATE_PROVINCE,
	COUNTRY_NAME,
	REGION_NAME
) 

LAG = '10 MINUTES' 
REFRESH_MODE = AUTO 
INITIALIZE = ON_CREATE 
WAREHOUSE = COMPUTE_WH
 AS 

 SELECT  
  E.EMPLOYEE_ID,   
  E.JOB_ID,   
  E.MANAGER_ID,   
  E.DEPARTMENT_ID,  
  D.LOCATION_ID,  
  L.COUNTRY_ID,  
  E.FIRST_NAME,  
  E.LAST_NAME,  
  E.SALARY,  
  E.COMMISSION_PCT,  
  D.DEPARTMENT_NAME,  
  J.JOB_TITLE,  
  L.CITY,  
  L.STATE_PROVINCE,  
  C.COUNTRY_NAME,  
  R.REGION_NAME  
FROM  
  EDW.EMPLOYEES E,  
  EDW.DEPARTMENTS D,  
  EDW.JOBS J,  
  EDW.LOCATIONS L,  
  EDW.COUNTRIES C,  
  EDW.REGIONS R  
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  
  AND D.LOCATION_ID = L.LOCATION_ID  
  AND L.COUNTRY_ID = C.COUNTRY_ID  
  AND C.REGION_ID = R.REGION_ID  
  AND J.JOB_ID = E.JOB_ID
  ORDER BY E.EMPLOYEE_ID
  ;